jobs:
  include:
    - stage: pre-test
      script:
        ls -lR
        touch pre-test.ran
      script:
        ls -lR
        touch pre-test2.ran
    - stage: test
      script:
        ls -lR
        touch test.ran
