language: c

cache:
  directories:
    - build

stages:
  - compile
  - run

env:
  - MODE=symmetric
  - MODE=nonsym

jobs:
  include:
    - stage: compile
      env: MODE=nonsym
      script:
      - touch build/compile.$MODE
      - ls -lR
    - stage: compile
      env: MODE=symmetric
      script:
      - touch build/compile.$MODE
      - ls -lR
    - stage: run
      env: MODE=nonsym
      script:
      - ls -lR
    - stage: run
      env: MODE=symmetric
      script:
      - ls -lR
