language: c

cache:
  directories:
    - build

stages:
  - compile
  - test
  - cleanup

env:
  - MODE=symmetric
  - MODE=nonsym

install:
  - ls -lR
  - cp testing/{configure,Makefile} . && chmod +x configure
  - ls -lR

jobs:
  include:
    - &compile-code
      stage: compile
      env: MODE=nonsym
      script:
      - touch build/compile.$MODE
      - ls -lR
    - <<: *copmile-code
      env: MODE=symmetric
