language: c

cache:
  directories:
    - build

jobs:
  include:
    - stage: pre-test
      - script:
        - rm -rf build ; mkdir build
        - touch build/pre-test1.ran
        - ls -lRA
      - script:
        - rm -rf build ; mkdir build
        - touch build/pre-test2.ran
        - ls -lRA
    - stage: test
      - script:
        - touch test.ran
        - ls -lRA
