language: c

cache:
  directories:
    - build

stages:
  - pre-test
  - build-fms
  - compile
  - test

env:
  - MODE=repro
  - MODE=debug

jobs:
  include:
    - stage: pre-test
      script:
      - rm -rf build ; mkdir build
      - touch build/pre-test1.ran
      - ls -lR
    - stage: build-fms
      script:
      - touch build/fms.built
      - ls -lR
    - stage: compile
      script:
      - touch build/compile.repro
      - ls -lR
    - stage: compile
      env: MODE=debug
      script:
      - touch build/compile.debug
      - ls -lR
    - stage: test
      script:
      - ls -lR
