language: c

cache:
  directories:
    - build

stages:
  - check and compile
  - test
  - cleanup

env:
  - MODE=symmetric
  - MODE=nonsym

install:
  - ls -lR
  - cp testing/{configure,Makefile} . && chmod +x configure
  - ls -lR

jobs:
  include:
    - stage: check and compile
      env: JOB="Check code"
      script:
      - echo "Run code check"
    - &compile-code
      stage: check and compile
      env: MODE=symmetric
      script:
      - touch build/compile.$MODE
      - ls -lR
    - <<: *compile-code
      env: MODE=nonsym
    - &clean-build
      stage: cleanup
      env: MODE=symmetric
      script:
      - rm build/*
      - ls -lR
    - <<: *clean-build
      env: MODE=nonsym
    - stage: test
      install: skip
      env: JOB="Other test"
      script:
      - echo "Other TEST"
      - ls -lR
    - &run-tests
      stage: test
      env: MODE=symmetric
      script:
      - echo Test 1
      - ls -lR
      stage: test
      env: MODE=symmetric
      script:
      - echo Test 2
      - ls -lR
    - <<: *run-tests
      env: MODE=nonsym
