language: c

cache:
  directories:
    - build

stages:
  - compile
  - test

env:
  - MODE=symmetric
  - MODE=nonsym

matrix:
  exclude:
    - env: MODE=symmetric
    - env: MODE=nonsym

jobs:
  include:
    - stage: compile
      env: MODE=nonsym
      script:
      - touch build/compile.$MODE
      - ls -lR
    - stage: compile
      env: MODE=symmetric
      script:
      - touch build/compile.$MODE
      - ls -lR
    - stage: test
      #env: MODE=nonsym
      script:
      - ls -lR
    - env: MODE=symmetric
      script:
      - ls -lR
