language: c

cache:
  directories:
    - build

stages:
  - pre-test
  - build-fms
  - compile
  - test

jobs:
  include:
    - stage: pre-test
      script:
      - rm -rf build ; mkdir build
      - touch build/pre-test1.ran
      - ls -lR
    - stage: build-fms
      script:
      - touch build/fms.built
      - ls -lR
    - stage: compile
      script:
      - touch build/compile.1
      - ls -lR
    - script:
      - touch build/compile.2
      - ls -lR
          - stage: compile
    - stage: test
      script:
      - ls -lR
