language: c

cache:
  directories:
    - build

stages:
  - compile
  - test
  - cleanup

env:
  - MODE=symmetric
  - MODE=nonsym

install:
  - ls -lR
  - cp testing/{configure,Makefile} . && chmod +x configure
  - ls -lR

jobs:
  include:
    - &compile-code
      stage: compile
      env: MODE=symmetric
      script:
      - touch build/compile.$MODE
      - ls -lR
    - &clean-build
      stage: cleanup
      env: MODE=symmetric
      script:
      - rm build/*
      - ls -lR
    - stage: test
      install: skip
      env: JOB="Other test"
      script:
      - echo "Other TEST"
      - ls -lR
    - <<: *compile-code
      env: MODE=nonsym
    - <<: *clean-build
      env: MODE=nonsym
